# Generated by Django 2.0.1 on 2018-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_auto_20180117_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='title_original_article',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='text',
            field=models.TextField(max_length=8000),
        ),
    ]
