# Generated by Django 2.0 on 2018-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_auto_20180123_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='comment_author',
            field=models.TextField(default='No comment from the author.', max_length=3000),
            preserve_default=False,
        ),
    ]
